# -*- coding: utf-8 -*-
"""po.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GObtTqvNtDvaVWSjSm4b_LrJJUpuacIg
"""

from pdb_manip_py import pdb_manip
# Create a Coor object
coor_1hsg = pdb_manip.Coor()
coor_1hsg.get_PDB('1hsg', 'data/1hsg.pdb')


# Select res_name MK1
lig_coor = coor_1hsg.select_part_dict(selec_dict={'res_name': ['MK1']})
# Save the ligand coordinates
lig_coor.write_pdb('data/lig.pdb')


# To hide this cell add the following info in the cell metadata:
# "nbsphinx": "hidden"
import nglview as nv
nv.write_html('../_static/lig.html', [view_lig])
from IPython.display import IFrame


# Unecessary, only need to nglview online:
IFrame(src='../_static/lig.html', width=800, height=300)



# Keep only the amino acids
rec_coor = coor_1hsg.select_part_dict(selec_dict={'res_name': pdb_manip.PROTEIN_RES})
rec_coor.write_pdb('data/rec.pdb')


# To hide this cell add the following info in the cell metadata:
# "nbsphinx": "hidden"
import nglview as nv
nv.write_html('../_static/rec.html', [view_rec])
from IPython.display import IFrame


# Unecessary, only need to nglview online:
IFrame(src='../_static/rec.html', width=800, height=300)


from docking_py import docking

test_dock = docking.Docking('test', lig_pdb='data/lig.pdb', rec_pdb='data/rec.pdb')
test_dock.prepare_ligand()



test_dock.prepare_receptor()


test_dock.run_docking(out_pdb='test_dock.pdb',
                      num_modes=10,
                      energy_range=10,
                      exhaustiveness=16,
                      dock_bin='smina')


rmsd_list = test_dock.compute_dock_rmsd(test_dock.lig_pdbqt)
print(rmsd_list)